version: '3.8'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: game
    ports:
      - '3306:3306'
  backend:
    build: ./backend/backend
    ports:
      - '8080:8080'
    depends_on:
      - mysql
  express:
    build: ./express
    ports:
      - '3000:3000'
  frontend:
    build: ./frontend
    ports:
      - '9000:9000'
    depends_on:
      - backend
      - express

